name: run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.4'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        export DJANGO_SETTINGS_MODULE=project_b_07.settings  # Adjust to your settings module path
        export DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db
        export DJANGO_SECRET_KEY=test_secret_key

    - name: Run Django tests
      run: |
        python manage.py migrate
        python manage.py test

    - name: Run pytest
      run: |
        export DJANGO_SETTINGS_MODULE=project_b_07.settings
        PYTHONPATH=. pytest
